version: '3'

services:
  postgres:
    build:
      context: ./database-postgresql
      dockerfile: Dockerfile
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - 3-tier-app_network

  backend:
    build:
      context: ./backend-flask
      dockerfile: Dockerfile
    container_name: backend-flask
    restart: always
    ports:
      - "5000:5000"
    networks:
      - 3-tier-app_network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: frontend-react
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - 3-tier-app_network

  nginx:
    build:
      context: ./reverse-proxy-nginx
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - 3-tier-app_network
    depends_on:
      - frontend
      - backend
      

networks:
  3-tier-app_network:
    driver: bridge
