version: '3'

services:
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: frontend-react
    restart: always
    ports:
      - "3000:3000"
    networks:
      - 3-tier-app_network

  nginx:
    build:
      context: ./reverse-proxy-nginx
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - 3-tier-app_network
    depends_on:
      - frontend

networks:
  3-tier-app_network:
    driver: bridge

   